#!/usr/bin/env node
/**
 * End-to-end verification against a real DSH boot.
 *
 * This is the layer unit tests cannot reach: whether the loader activates the
 * plugin, whether Cordis hands it the services the structural types assume,
 * whether a real `settings.mutate()` lands in a profile patch file, and whether
 * the whole wiring works against the harness's own live directory.
 *
 * It caught two defects that no unit test could: `ctx.setTimeout` throwing
 * `cannot get property "timer" without inject`, and a `startupDelayMs: 0`
 * guard that silently disabled the startup pass.
 *
 * What it does, entirely inside this package's `.e2e/` scratch directory:
 *
 *   1. builds a throwaway `DSH_HOME` with one `scratch` profile,
 *   2. links the packages of the profile you point it at, so the real
 *      `dsh-base` bundle resolves, plus this package under its own name,
 *   3. writes a patch that mounts a real `llm-pi-ai` route against a local
 *      fake listing endpoint and mounts this plugin with `startupDelayMs: 0`,
 *   4. boots the real `dsh --profile scratch`,
 *   5. asserts the profile patch file gained the endpoint's new model while the
 *      hand-written entry survived untouched.
 *
 * Usage:
 *   DSH_PROFILE_DIR=~/.dsh/profiles/desktop node scripts/e2e.mjs
 *
 * Nothing outside `.e2e/` is read beyond the package links, and no server other
 * than the local fake endpoint is started.
 */
import { spawn } from 'node:child_process'
import { createServer } from 'node:http'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const PACKAGE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const E2E_DIR = join(PACKAGE_DIR, '.e2e')
const SCRATCH_HOME = join(E2E_DIR, 'dsh-home')
const PROFILE = join(SCRATCH_HOME, 'profiles', 'scratch')
const PATCH = join(PROFILE, 'cordis.patch.yml')
const PORT = Number(process.env.E2E_PORT ?? 38731)
const BOOT_TIMEOUT_MS = Number(process.env.E2E_TIMEOUT_MS ?? 60_000)

/** The profile whose packages get linked in, and where the dsh CLI lives. */
function locateProfile() {
  const explicit = process.env.DSH_PROFILE_DIR
  const candidates = [explicit, join(homedir(), '.dsh', 'profiles', 'desktop')].filter(Boolean)
  for (const candidate of candidates) {
    const profilesRoot = dirname(candidate)
    const modules = join(profilesRoot, 'node_modules')
    const dshBin = join(modules, '@deepseek-ai', 'dsh', 'lib', 'bin.js')
    if (existsSync(dshBin)) return { modules, dshBin }
  }
  throw new Error(
    'could not locate the dsh CLI; set DSH_PROFILE_DIR to a profile directory (for example ~/.dsh/profiles/desktop)',
  )
}

const log = (message) => console.log(`[e2e] ${message}`)

/** The listing the fake endpoint serves. */
const FAKE_MODELS = {
  object: 'list',
  data: [
    { id: 'e2e-existing', name: 'E2E Existing', context_length: 8192 },
    {
      id: 'e2e-brand-new',
      name: 'E2E Brand New',
      context_length: 262_144,
      top_provider: { max_completion_tokens: 65_536 },
    },
  ],
}

/** The route and plugin configuration the scratch profile mounts. */
const PATCH_BODY = `# Generated by scripts/e2e.mjs — throwaway.
- id: llm-pi-ai
  name: '@deepseek-ai/dsh-llm-pi-ai'
  config:
    providers:
      e2e-local:
        displayName: E2E Local
        api: openai-completions
        baseURL: http://127.0.0.1:${String(PORT)}/v1
        models:
          - id: e2e-existing
            name: Hand Written
            contextWindow: 4096

- insert:
    - id: llm-pi-ai-live
      name: 'dsh-llm-pi-ai-live'
      config:
        enabled: true
        startupDelayMs: 0
        intervalMs: 0
        timeoutMs: 15000
        dryRun: false
        enrichFromCatalog: true
        toolEnabled: true
        # The route is not in pi-ai's catalog, so its models have no reasoning
        # capability at all until something declares one.
        reasoning:
          enabled: true
          rules:
            - provider: 'e2e-local'
              model: '*'
              efforts:
                off: null
                high: high
`

/** Build the throwaway home and profile, linking the real packages in. */
function prepare(modules) {
  rmSync(E2E_DIR, { recursive: true, force: true })
  mkdirSync(PROFILE, { recursive: true })
  writeFileSync(join(PROFILE, 'cordis.yml'), '[]\n')
  writeFileSync(
    join(PROFILE, 'package.json'),
    `${JSON.stringify(
      { name: 'dsh-profile-e2e-scratch', private: true, dependencies: {}, dsh: { profile: { bundles: ['@deepseek-ai/dsh-base'] } } },
      null,
      2,
    )}\n`,
  )
  writeFileSync(PATCH, PATCH_BODY)

  const nodeModules = join(PROFILE, 'node_modules')
  mkdirSync(nodeModules, { recursive: true })
  for (const entry of readdirSync(modules)) {
    if (entry.startsWith('.')) continue
    symlinkSync(join(modules, entry), join(nodeModules, entry))
  }
  // The plugin under test must be resolvable by its package *name*: the loader
  // imports a bare specifier, not a directory path.
  symlinkSync(PACKAGE_DIR, join(nodeModules, 'dsh-llm-pi-ai-live'))
  log(`scratch profile ready at ${PROFILE}`)
}

/** Start the fake listing endpoint. */
function startFakeEndpoint() {
  const hits = []
  const server = createServer((request, response) => {
    hits.push(request.url)
    if (request.url?.endsWith('/models')) {
      response.writeHead(200, { 'content-type': 'application/json' })
      response.end(JSON.stringify(FAKE_MODELS))
      return
    }
    response.writeHead(404).end('not found')
  })
  return new Promise((resolvePromise, reject) => {
    server.once('error', reject)
    server.listen(PORT, '127.0.0.1', () => resolvePromise({ server, hits }))
  })
}

/** Boot the profile and resolve when the assertion holds or the timeout fires. */
async function boot(dshBin) {
  const child = spawn(process.execPath, [dshBin, '--profile', 'scratch'], {
    cwd: E2E_DIR,
    env: { ...process.env, DSH_HOME: SCRATCH_HOME },
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  let output = ''
  child.stdout.on('data', (chunk) => {
    output += String(chunk)
  })
  child.stderr.on('data', (chunk) => {
    output += String(chunk)
  })

  const deadline = Date.now() + BOOT_TIMEOUT_MS
  return {
    child,
    get output() {
      return output
    },
    /** Wait until the patch file contains `needle`. */
    async waitFor(needle) {
      while (Date.now() < deadline) {
        const current = readFileSync(PATCH, 'utf8')
        if (current.includes(needle)) return true
        await new Promise((r) => setTimeout(r, 500))
      }
      return false
    },
    stop() {
      child.kill('SIGTERM')
      setTimeout(() => child.kill('SIGKILL'), 1500).unref()
    },
  }
}

/** Read `providers.e2e-local.models` out of the written patch, minimally. */
function readModels(text) {
  const models = []
  let inModels = false
  for (const line of text.split('\n')) {
    // A new top-level patch entry ends the route section.
    if (inModels && /^- /.test(line)) break
    if (/^\s+models:\s*$/.test(line)) {
      inModels = true
      continue
    }
    if (!inModels) continue
    const id = /^\s+-\s+id:\s*(\S+)\s*$/.exec(line)
    if (id) {
      models.push({ id: id[1] })
      continue
    }
    // A sibling key at or above the `models:` indent ends the list.
    if (line.trim().length > 0 && !line.trimStart().startsWith('-') && /^\s{0,6}\S/.test(line)) break
  }
  return models
}

async function main() {
  const { modules, dshBin } = locateProfile()
  log(`using packages from ${modules}`)

  prepare(modules)
  const { server, hits } = await startFakeEndpoint()
  log(`fake listing endpoint on http://127.0.0.1:${String(PORT)}`)

  const session = await boot(dshBin)
  let ok = false
  let failure = ''
  try {
    ok = await session.waitFor('e2e-brand-new')
    if (!ok) failure = `the plugin never wrote the new model within ${String(BOOT_TIMEOUT_MS)}ms`
  } finally {
    session.stop()
    server.close()
  }

  const text = readFileSync(PATCH, 'utf8')
  const models = readModels(text)
  const ids = models.map((model) => model.id)

  if (ok) {
    if (!ids.includes('e2e-existing')) {
      ok = false
      failure = 'the hand-written entry was lost'
    } else if (ids.indexOf('e2e-existing') > ids.indexOf('e2e-brand-new')) {
      ok = false
      failure = 'appended models were not placed after the hand-written entry'
    } else if (!/e2e-brand-new[\s\S]*?maxTokens:\s*65536/.test(text)) {
      ok = false
      failure = 'the appended entry did not carry the endpoint-reported output cap'
    } else if (!/e2e-brand-new[\s\S]*?reasoningEfforts:[\s\S]{0,80}?high:\s*high/.test(text)) {
      ok = false
      failure = 'the appended entry did not receive a reasoning declaration'
    } else if (!/e2e-existing[\s\S]{0,200}?reasoningEfforts:/.test(text)) {
      ok = false
      failure = 'the pre-existing third-party entry, which declared no reasoning, was left without one'
    } else if (!hits.some((url) => url?.endsWith('/v1/models'))) {
      ok = false
      failure = 'the fake endpoint was never interrogated'
    }
  }

  const reasoned = /e2e-brand-new[\s\S]*?reasoningEfforts:[\s\S]{0,80}?high:\s*high/.test(text)
  console.log('')
  console.log(`  route models after boot : ${ids.join(', ') || '(none)'}`)
  console.log(`  reasoning declared      : ${reasoned ? 'yes — off/high on both third-party models' : 'no'}`)
  console.log(`  endpoint hits           : ${hits.join(', ') || '(none)'}`)
  console.log(`  result                  : ${ok ? 'PASS' : `FAIL — ${failure}`}`)
  if (!ok && session.output.trim().length > 0) {
    console.log('\n--- boot output ---')
    console.log(session.output.split('\n').slice(-40).join('\n'))
  }
  console.log('')
  process.exit(ok ? 0 : 1)
}

await main()
